services:
  backend:
    build: ./backend
    image: sibeisafe-backend:latest
    container_name: sibeisafe-backend
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: sibeisafe-frontend:latest
    container_name: sibeisafe-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:18.4-alpine
    container_name: sibeisafe-db
    environment:
      POSTGRES_DB: sibeisafe

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_PASSWORD}

      DB_USER: db_user
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
      - ./create-user.sh:/docker-entrypoint-initdb.d/create-user.sh
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  redis:
    image: redis:8.0.1-alpine
    container_name: sibeisafe-redis
    restart: unless-stopped


volumes:
  pgdata: